sous-chefs/docker

README.md
providers/container.rb
resources/container.rb

It corresponds to `--add-host` CLI argument, described here:
https://docs.docker.com/reference/run/.

Add additional_host attribute to container resource

---

providers/container.rb

On at least 2 of my servers the `docker stop` command runs unusually slow. As the benchmark below shows, stopping a container seems to take around 20s more than the graceful stop delay. In this PR, I workaround the issue by increasing the shell_out timeout from its current 15 (already a workaround) to 30 seconds.
```
root@staging2-ng:~# time docker stop --time=1 125b758d437f
125b758d437f
real	0m22.546s
user	0m0.010s
sys	0m0.007s
root@staging2-ng:~# time docker stop --time=1 fd00d6158eaa
fd00d6158eaa
real	0m22.698s
user	0m0.007s
sys	0m0.010s
root@prod1-ng:~# time docker stop --time=1 1 509ca18cf34e
509ca18cf34e
real	0m23.603s
user	0m0.009s
sys	0m0.007s
```
Have to investigate the issue more and see if I should open a bug report on docker github, but since the problem shows on multiple …

Lengthen shell_out timeout as workaround for slow docker_container action stop.

---

providers/container.rb

When you use `port.gsub!` - you are changing the value  port variable
itself, and as long as the value is not local to this method, but
is a part of new_resource record (when it's passed as an array or
string) - the previous code will modify `new_resource.port` instance
variable.

Fix accidental port changing when using systemd templates.

---

README.md
test/cookbooks/docker_test/CHANGELOG.md
test/cookbooks/docker_test/files/default/tests/minitest/container_lwrp_test.rb
test/cookbooks/docker_test/files/default/tests/minitest/image_lwrp_test.rb
test/cookbooks/docker_test/recipes/container_lwrp.rb
test/cookbooks/docker_test/recipes/image_lwrp.rb
test/shared/spec/container_spec.rb
test/shared/spec/image_spec.rb

bflad's testcontainerd wasn't working with newer versions of Docker.
This commit replaces that container with one from tduffields' repo.

Replace outdated testcontainerd

---

README.md
resources/container.rb

This very modest PR allows String values for docker_container memory attribute.
Currently, the docker_container resource only allows `Fixnum` values for the attribute (in other words, memory value is implicitly in bytes) but the docker [documentation](https://docs.docker.com/reference/run/#runtime-constraints-on-cpu-and-memory) says that the `docker run --memory` parameter supports optional units. It is also possible to specify different memory and memory+swap limits.
With this PR I can set `docker.memory = '1G'` or `docker.memory = '150m,200m'`, while still allowing for Fixnum memory values as before.

Allow docker_container memory to have String value (eg. memory='1G').

---

templates/default/docker.conf.erb

This PR brings our upstart docker service template up to date with the original at https://github.com/docker/docker/blob/master/contrib/init/upstart/docker.conf .
I found out about the issue when upgrading to lxc-docker 1.5.0; dpkg asked me if I want to replace the `/etc/init/docker.conf` file or keep my change. Ironically, the changes in the file are related to fixing an issue that I reported a while ago on the docker github that got merged last December.

Updated the /etc/init/docker.conf template.

---

providers/image.rb

When you are using custom registries `pull` command will not trigger notifications as expected because it will compare wrong ids.

Use registry on image inspection

---

templates/debian/docker-container.sysv.erb

`status_of_proc "$DAEMON" "$NAME"` will actually check that ANY docker process is running, not the needed one.

Fix checking docker container status on debian

---

providers/container.rb
spec/systemd_spec.rb
spec/sysv_spec.rb
spec/upstart_spec.rb

```
Inspecting 53 files
.................C................................CCC
Offenses:
providers/container.rb:184:60: C: Use %r around regular expression.
new_resource.container_name || new_resource.image.gsub(/^.*\//, '')
^^^^^^^
providers/container.rb:261:47: C: Use %r around regular expression.
ps['names'] = ps['names'].split(',').grep(/\A[^\/]+\Z/).join(',') # technical names always contain a '/'
^^^^^^^^^^^^
spec/systemd_spec.rb:256:9: C: Use %r around regular expression.
/^Environment="NO_PROXY=host1.example.com,111.111.111.0\/24"/)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/systemd_spec.rb:490:9: C: Use %r around regular expression.
/^Environment="TMPDIR=\/tmp"$/)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/sysv_spec.rb:267:9: C: Use %r around regular expression. …
```

Rubocop fixes for regexes

---

providers/container.rb
templates/default/sv-docker-container-finish.erb

fixes #284, runit finish script to stop a container

---

recipes/package.rb

Redhat 7 ships the `docker` package in the `rhel-7-server-extras-rpms` repo.
See: https://docs.docker.com/installation/rhel/#red-hat-enterprise-linux-7-installation

redhat 7 does not need the epel repository

---

attributes/default.rb
recipes/default.rb
templates/default/docker.socket.erb

The latest RHEL 7 docker rpm docker-1.4.1-37.el7 does not create a docker group anymore. This breaks the socker.socket unit file which defaults to *docker* for the socket group.
This post explains some details for not shipping a docker group by default for security reasons some more:
https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2015-January/msg00034.html

Fix docker.socket unit for RHEL7

---

attributes/default.rb
templates/default/docker.service.erb

More information about systemd changes below, which will default docker host to `fd://` among other unit file changes.
`ExecStart=... -H fd://`:
* https://github.com/docker/docker/commit/076ac1d7d212c3a81a401a2fba8b9965bc26df16
`LimitCORE=infinity`:
* https://github.com/docker/docker/commit/ae9cdbbde7824951b124a648e897ac4c291108e3
* http://www.freedesktop.org/software/systemd/man/systemd.exec.html#LimitCPU=
`MountFlags=slave`:
* https://github.com/docker/docker/commit/eb76cb2301fc883941bc4ca2d9ebc3a486ab8e0a
* http://www.freedesktop.org/software/systemd/man/systemd.exec.html#MountFlags=

Default systemd to fd:// as well as use upstream MountFlags=slave and LimitCORE=infinity

---

templates/debian/docker.sysv.erb
templates/default/docker.sysv.erb

Non-Debian SysV changes to match upstream:
* `check_for_cleanup`: https://github.com/docker/docker/commit/05d04843e6b80f131c07882c882f7e4da018a306
* `killproc -d 300`: https://github.com/docker/docker/commit/640d2ef6f54d96ac4fc3f0f745cb1e6a35148607
* `unshare`: https://github.com/docker/docker/commit/6bb65864589fbd720622cbd795763d108999a366
* part of `util-linux-ng` package, installed on almost all CentOS/RHEL 6+ boxes by default
Debian SysV changes to match upstream:
* `DOCKER_SSD_PIDFILE`: https://github.com/docker/docker/commit/c11fadb282ea7e96eef2280a5e422fd2c94e8c45
* `set -e` / `status_of_proc $DOCKER_DESC`: https://github.com/docker/docker/commit/478fdaf93353c70a26c0043dadb650fd2f101c40
* `Should-Start` / `Should-Stop`: https://github.com/docker/docker/commit/36d913078b7ea0138dbc5d5 …

Update docker daemon SysV init scripts with upstream improvements

---

README.md
attributes/default.rb
spec/systemd_spec.rb
spec/sysv_spec.rb
spec/upstart_spec.rb

Further deprecate daemon restart flag by default, which interferes with restart policies

---

providers/container.rb
templates/default/docker-container.sysv.erb
test/cookbooks/docker_test/files/default/tests/minitest/support/helpers.rb

The `-notrunc` flag causes a very annoying warning message to stderr.
This replaces the last usage (sysv init file), a comment, and the
minitests.

Fixed remaining `-notrunc` usages

---

templates/default/docker-container.sysv.erb

in recent version of docker, --no-trunc includes extra information about
links to other containers. This caused the ps command used for status to
return more than one container in certain cases. This is a fix for issue #323

removed --no-trunc from docker container status

---

providers/container.rb
resources/container.rb

As per https://github.com/bflad/chef-docker/issues/320 - the container resource wasn't allowing tag overrides. I've set the tag to default to "latest" and allowed this to be overridden.

Fixes #320 - ability to specify a tag for a container image

---

resources/container.rb

This attribute was removed in [28217e](https://github.com/bflad/chef-docker/commit/28217e99f402c4fa716f2164985fc1cdf145b6aa#diff-b0b27265fc5f4128b47410ecb3085361L60) but is still used in the corresponding [provider](https://github.com/bflad/chef-docker/blob/master/providers/container.rb#L392). I'm assuming its removal was unintentional.
Its absence is causing a NoMethodError:
```
....
================================================================================
Error executing action `run` on resource 'docker_container[consul]'
================================================================================
NoMethodError
-------------
undefined method `ulimit' for LWRP resource docker_container from cookbook docker
...
```

Add ulimit attribute back to container resource

---

resources/container.rb

With v0.40.0, I got the following error:
```
NoMethodError: undefined method `ulimit' for LWRP resource docker_container from cookbook docker
```

Declare ulimit parameter in the resource

---

templates/amazon/docker.sysv.erb

DOCKER_OPTS was not being honored during startup of docker on Amazon
Linux. The init.d script was not referencing the correct file.

init.d script in amazon did not reference DOCKER_OPTS

---

README.md

`Usage: docker run [OPTIONS] IMAGE [COMMAND] [ARG...]`
It took me quite a long time to figure out that the `[ARG...]` part of the command should be captured in this way.  I hope this will save others some time!

Example of running a container with ARGs

---

libraries/helpers.rb
spec/docker_service_test/socket_spec.rb

I noticed this bug while I was reading through the code so I figured I'd send a patch with a test.

Use docker_kernel instead of docker_arch in parsed_checksum

---

libraries/resource_docker_container.rb

PR #363 allows port to be an array but the resource attribute restricts only to a string.

allow port to be a kind_of array

---

libraries/matchers.rb

Just noticed this matcher was missing when running my spec tests

Add ChefSpec matcher for run_if_missing action

---

README.md

The `ip` attribute for the service was wrong.

Fixed ip description

---

metadata.rb

Add the `source_url` and `issues_url` keys to the metadata

Supermarket should display source and issues links

---

libraries/helpers.rb

```
[2015-08-23T22:20:17+00:00] ERROR: docker_service[default] (scalingo::docker line 12) had an error: NameError: No resource, method, or local variable named `storage_driver' for `Chef::Provider::DockerService::Upstart ""'
```

Fix 'parsed_storage_driver' method error

---

libraries/helpers.rb
libraries/resource_docker_service.rb

As it is defined to be a boolean in the resource, the only possible
values allowed to the user are true or false. Let docker use its default
value instead of setting a default flag.
If the user knows what he's doing he'll be able to give a specific value
to the flag.

Correctly define ip_forward flag, not present by default in opts

---

libraries/provider_docker_service_sysvinit.rb
spec/docker_service_test/sysvinit_spec.rb
test/cookbooks/docker_service_test/recipes/sysvinit.rb

node['platform'] returns a specific flavor of rhel (like Redhat, Centos, etc), whereas node['platform_family'] is more general, returning 'rhel' for both Redhat and Centos. I updated the sysvinit provider to reflect this.
Also added a couple of tests for Chef::Provider::DockerService::Sysvinit on a Centos7 box.

GH-395 Check if platform_family matches rhel, rather than redhat, in Sysvinit

---

libraries/matchers.rb

The matcher `create_docker_container` was missing. Upon further inspection, it looked as if more actions were missing for resources.
I've refactored matchers.rb to generate matchers introspectively to prevent forgetting to add/remove them in the future.

Prevent missing matchers

---

libraries/helpers.rb

These arguments require double dashes as noted by the documentation.
```shell
flag needs an argument: -p
See '/usr/bin/docker daemon --help'.
flag provided but not defined: -pidfile
See '/usr/bin/docker daemon --help'.
```

fix arguments in helpers

---

README.md
libraries/provider_docker_container.rb
libraries/provider_docker_image.rb
libraries/resource_docker_container.rb
libraries/resource_docker_image.rb
test/cookbooks/docker_test/recipes/container.rb
test/cookbooks/docker_test/recipes/image.rb

i split the api timeouts into two attributes matching the docker api. not sure if you want to combine this into one attrib or not, if you do let me know and i can change it.
resolves #403

adding ability to set docker api read write timeouts

---

libraries/helpers_service.rb

If a user wanted to use the `source` attribute for the `docker_service` LWRP they need to specify a custom `checksum` attribute as well. The `parsed_checksum` helper method was ignoring this custom attribute and always providing the LWRP with a hard-coded checksum which matched with the default docker binary source.

`parsed_checksum` helper for docker_service returns new_resource.checksum if specified

---

libraries/helpers_service.rb
libraries/resource_docker_service.rb

Currently if the `storage_opt` attribute for docker_service is
specified on the docker_service resource it's value will be passed
to the docker daemon prefixed by a single `--storage-opt` flag.
Each storage option passed to the docker daemon requires being
prefixed with it's own `--storage-opt` flag. Because of this
prefixing the value of `storage_opt` with a single `--storage-opt`
flag is a bug, as it makes passing multipe storage options to
the docker daemon hard to accomplish.
To correct this I've replaces the `storage_opt` attribute for
docker_service with `storage_opts` and accept an Array. Then in
the `docker_opts` helper method I collect the value of the array
and prefix each item with it's own `--storage-opt` flag.

Change storage_opt attrib to storage_opts in docker_service LWRP

---

libraries/provider_docker_registry.rb
libraries/provider_docker_service_systemd.rb
spec/docker_service_test/sysvinit_spec.rb

The rescue block allowed multiple login attempts, but the exception was not resurfaced when the retry limit was reached.

GH-398 Raise AuthenticationError if number of retries on login is exceeded

---

libraries/provider_docker_service.rb

I noticed the [docker_service](https://github.com/bflad/chef-docker/blob/master/libraries/resource_docker_service.rb#L10) resource doesn't actually specify `:enable` action, so this just cleans that up.
Note: this depends on #425 to be merged in for the tests to pass.

Remove nonexistent action :enable from docker_service

---

libraries/helpers_service.rb
spec/docker_service_test/socket_spec.rb

While attempting to revive the [`docker_service` kitchen test suite](https://github.com/bflad/chef-docker/blob/master/.kitchen.yml#L63-L73), I noticed that Chef wasn't able to actually fetch the docker binary from the `get.docker.io` URL:
```sh-session
Recipe: docker_service_test::socket
* docker_service[default] action createRecipe: <Dynamically Defined Resource>
* remote_file[/usr/bin/docker] action create[2015-09-16T14:36:09+00:00] WARN: remote_file[/usr/bin/docker] cannot be downloaded from https://get.docker.io/builds/Linux/x86_64/docker-1.6.2: 503 "Service Unavailable"
================================================================================
Error executing action `create` on resource 'remote_file[/usr/bin/docker]'
============================================================== …
```

Use get.docker.com instead of get.docker.io

---

README.md
libraries/helpers_service.rb
libraries/resource_docker_service.rb

A simple PR to update the whitelist of logging drivers supported by the docker service. It also adds a new `log_opts' attribute to the docker_service, which allows to configure the exotic logging drivers such as fluentd or syslog.
The list of supported logging drivers can be found at the top of this page: https://docs.docker.com/reference/logging/overview/

Support more logging drivers and allow specifying logging driver options

---

README.md
libraries/helpers_service.rb
libraries/resource_docker_service.rb

Per [documentation](http://docs.docker.com/reference/commandline/daemon/), the docker daemon accepts multiple --dns options.
This PR allows the `docker_service` dns attribute to be either a String (like today) or an Array of string.

Allow specifying multiple dns servers to docker_service.

---

Rakefile

After running `bundle install` on a fresh copy of this repository, running `bundle exec rake -T` (or any other rake command) would fail with Kitchen::ClientError when no kitchen-vagrant driver is installed.
I just wanted to run the rubocop task so I made this PR.

Prevents `rake -T` from blowing when no kitchen-vagrant driver installed.

---

libraries/provider_docker_container.rb
test/cookbooks/docker_test/recipes/container.rb
test/integration/resources-162/serverspec/assert_functioning_spec.rb
test/integration/resources-171/serverspec/assert_functioning_spec.rb
test/integration/resources-182/serverspec/assert_functioning_spec.rb

This PR is my attempt at fixing #432.
For some reason, I was not able to run the serverspec ("kitchen setup" then "kitchen verify" are no-ops), so I ran my rspec examples manually on both resources-ubuntu-1404 and resources-ubuntu1504 instances after converging them.
My server spec example:
```ruby
describe command("docker ps -af 'name=unstarted_redeployer$'") do
its(:exit_status) { should eq 0 }
its(:stdout) { should_not match(/Up/) }
its(:stdout) { should match(/Created/) } if docker_version.to_f >= 1.8
end
```
The results (note the different container status pre and post docker 1.8).
On 14.04 (docker 1.6.2):
```sh
root@resources-ubuntu-1404:~# docker ps -a | grep redeployer
d8a8e41dc7e0        alpine:3.1               "nc -ll -p 7777 -e /   About a minute ago …
```

Redeploy unstarted containers using action_create instead of action_run.

---

libraries/_port_binding.rb
test/integration/resources-162/serverspec/assert_functioning_spec.rb
test/integration/resources-171/serverspec/assert_functioning_spec.rb
test/integration/resources-182/serverspec/assert_functioning_spec.rb

Fixes #427.
Validated by running `kitchen test resources-182-ubuntu-1404` (no time/bandwidth to run on all supported combinations).

Qualify port bindings with protocol even when implicitly tcp

---

libraries/provider_docker_container.rb
test/integration/resources-162/serverspec/assert_functioning_spec.rb
test/integration/resources-171/serverspec/assert_functioning_spec.rb
test/integration/resources-182/serverspec/assert_functioning_spec.rb

This PR fixes recent breakage in serverspec introduced by some of my recent PRs. Breakage log from @someara here: https://gist.github.com/someara/2066171ebcb5f3a95da5#file-gistfile1-txt-L590
First breakage was due using too strict matcher when parsing the docker inspect output in #439 
Second breakage was more serious and due to false positive when matching for 'unstarted containers' in #437

Fixed serverspec after #439 and #437 merges.

---

README.md
libraries/helpers_container.rb
libraries/provider_docker_container.rb
libraries/resource_docker_container.rb
test/cookbooks/docker_test/recipes/container.rb
test/integration/resources-162/serverspec/assert_functioning_spec.rb
test/integration/resources-171/serverspec/assert_functioning_spec.rb
test/integration/resources-182/serverspec/assert_functioning_spec.rb

This PR allows to configure logging on a per-container basis, when the logging driver or its configuration is different than the systemwide (docker_service) defaults.
It introduces two new attributes for docker_container:
- log_driver = %w( json-file syslog journald gelf fluentd none )
- log_opts = Array of "key=value" strings that are specific to each log-driver
Which work similarly to the eponymous attributes of the `docker_service` resource.
Use the new attribute like this:
```ruby
docker_container 'syslogger' do
command 'nc -ll -p 780 -e /bin/cat'
repo 'alpine'
tag '3.1'
log_driver 'syslog'
log_opts 'syslog-tag=container-syslogger'
end
```
The stubbed handling of docker_container log_config attribute has been fixed and updated to handle the 2 new attributes, which are an higher-level …

Added docker_container log_driver and log_opts attributes.

---

libraries/helpers_container.rb
libraries/provider_docker_container.rb

The handling of exposed_ports is tricky because some exposed_ports are injected from the image (EXPOSE instruction in Dockerfile). As such, we cannot rely on new_resource.exposed_ports and new_resource.port to declare which ports are actually be exposed.
The consequence is #446 where a container with multiple ports exposed from Dockerfile and at least one which is not bound (new_resource.port) is redeployed at every chef-run.
This PR fixes #446

Fix unwanted redeploys due to calculation of exposed_port changes.

---

libraries/helpers_container.rb
libraries/provider_docker_container.rb

This PR should fix #449.
The existing code already had a "update_volumes?" method, it was just not being used to compute the list of "resource_changes" in the docker container. I also handled a case where current_resource.volumes is nil (this happens in the test suite with the 'chef_container', where parsed_volumes is {"/opt/chef" => {}} while current_resource.volumes is nil; then obviously the container should be redeployed).

Treat docker_container volumes attribute as unmanaged to prevent redeploys.

---

libraries/resource_docker_container.rb

This PR sets the default value for `docker_container.memory_swap` to `-1` (unlimited) from the current value of `0` (which also means unlimited if I believe the [docker code](https://github.com/docker/docker/blob/dac92a8afbe0900641afa00e33e84e180d432239/vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go#L62)).
On some systems, I have noticed that setting that value to 0 in the cookbook results in a value of -1 being displayed in the output of `docker inspect -f '{{ .HostConfig.MemorySwap }}`.
This happens when:
- a positive value is provided for `docker_container.memory` (eg. `'128m'`)
- the system is running under some kernel versions (see below)
The consequence is that on affected systems, containers which specify a positive value for `docker_container.memory` …

Changed default docker_container memory_swap to prevent unwanted redeploys.

---

.travis.yml
Rakefile
libraries/provider_docker_service_systemd.rb

set foodcritic to fail on any tag during a travis-ci build, currently foodcritic just complains but returns 0 allowing the build to continue. 
removed the ignore on FC009 tag since that rule passes with the current code.
updating rake and travis-ci to be using the same args passed into foodcritic
foodcritic was complaining about the way platforms were passed, i think the current solution is the cleanest so added an ignore comment.

updates to foodcritic for rake and travis-ci

---

libraries/helpers_service.rb
libraries/provider_docker_service_execute.rb
templates/default/sysvinit/docker.erb
templates/default/upstart/etc.default.docker.erb

After trying out version 1.0.35 of this cookbook on ubuntu 14.04 (upstart), I found out that the chef-run was broken because of:
```sh
Chef::Mixin::Template::TemplateError (undefined method `docker_log' for Chef::Resource::DockerService) on line #6:
4: DOCKER="<%= @docker_bin %>"
5: 
6: <% if @config.docker_log %>
7: DOCKER_LOGFILE=<%= @config.logfile %>
8: <% end %>
```
So I made this PR to replace all occurrences of the `docker_log` helper (which returned the hardcoded `/var/log/docker.log` string) to use the newly introduced docker_service.logfile attribute (with the same default value).

Replace all occurences of `docker_log` helper with `docker_service.logfile`.

---

libraries/provider_docker_service_sysvinit.rb
templates/default/sysvinit/docker.erb

The template for the sysvinit script was broken on CentOS/Amazon Linux. In this commit, it's now passed `docker_bin` in similar fashion as the other templates for upstart and systemd.

Fix template error for sysvinit

---

README.md
libraries/helpers_service.rb
libraries/provider_docker_service.rb
libraries/provider_docker_service_execute.rb
libraries/provider_docker_service_systemd.rb
libraries/provider_docker_service_sysvinit.rb
libraries/provider_docker_service_upstart.rb
libraries/resource_docker_service.rb
templates/default/systemd/docker.service.erb
templates/default/sysvinit/docker.erb
templates/default/upstart/docker.conf.erb
templates/default/upstart/etc.default.docker.erb
test/cookbooks/docker_service_test/recipes/tls.rb

a lot of changes here. i did some cleanup in a couple of commits for clarity prior to the big tls changes.
i removed using the environment variables for the docker command since it doesnt match exact with the api. if a user had a cert and key in different locations it would have failed. there is now a docker_cmd to use when we need to shell out to docker cli. this takes care of any options we need to specify (tls and host atm).
the docker daemon uses multiple host commands, but the client only uses one so i created a parsing function for the connect_host. this should be expanded on later and should prioritize using the socket over tcp. for now though the function just returns the first element.
let me know how it tests out with test-kitchen.
resolves #468

fix for failed tls

---

README.md
libraries/helpers_connection.rb
libraries/helpers_container.rb
libraries/helpers_image.rb
libraries/provider_docker_container.rb
libraries/provider_docker_image.rb
libraries/resource_docker_container.rb
libraries/resource_docker_image.rb
test/cookbooks/docker_test/recipes/container.rb
test/cookbooks/docker_test/recipes/default.rb
test/cookbooks/docker_test/recipes/image.rb
test/integration/resources-162/serverspec/assert_functioning_spec.rb
test/integration/resources-171/serverspec/assert_functioning_spec.rb
test/integration/resources-182/serverspec/assert_functioning_spec.rb

-basic support for adding per-resource docker.connection, resolves #322.
-tls is currently not supported, but will be trivial to add support for and i will add when i have extra cycles to burn.

per-resource docker host

---

libraries/helpers_base.rb

https://github.com/chef/chef-rfc/blob/master/rfc054-resource-attribute-improvements.md#property_is_set
the default timeouts are not being set and it is from the property_is_set. described in the rfc above, property_is_set only returns true if the property has a value other than default.
test-kitchen keeps failing on image builds because we specify a timeout of 120 seconds, but it has been failing to set that.

removing property_is_set so timeout will be set to our defaults

---

.kitchen.yml
libraries/docker_container.rb
libraries/docker_image.rb
libraries/docker_tag.rb

added chef-client 12.4.3 and latest to kitchen for the time being. this was an issue present only in 12.4.3 and not in 12.5.1 because of compat_resource. we should test against both versions for a bit.
resolves #500 and #501

LocalJumpError caused by return nil

---

README.md
libraries/docker_container.rb
test/cookbooks/docker_test/recipes/container.rb

action run has become very stable since we switched to using the new custom resource. i think run should become the new default so containers will be redeployed on resource changes.

changing container resource to default action :run

---

libraries/helpers_container.rb

ok this passed with test-kitchen and the runtime is back to normal. my theory checked out correct.
resolves #510

check if the container finished before we were able to check state

---

libraries/docker_container.rb

removing image alias that doesnt have a property and is deprecated

---

README.md
libraries/docker_container.rb
libraries/docker_service.rb
libraries/helpers_service.rb
test/cookbooks/docker_test/recipes/default.rb
test/integration/resources-162/serverspec/assert_functioning_spec.rb
test/integration/resources-171/serverspec/assert_functioning_spec.rb
test/integration/resources-182/serverspec/assert_functioning_spec.rb

adding label support to the daemon. also, occasionally docker inspect returns container labels unsorted and causes rspec to fail; implemented fix for this.

daemon can accept multiple labels. updating README. string is valid

---

libraries/docker_container.rb
libraries/docker_image.rb

the only small issue with this, which isnt really harmful, is action :pull will actually pull the latest image even with whyrun because the comparison happens after we create a new image and compare old id with new id. still researching on how to compare local and repo image without performing an Image.create.
resolves #522

adding why_run support

---

templates/default/upstart/docker.conf.erb

My proposed fix for #536.
There is no integration test, but if there was a simple typo in the init file then the docker daemon would not be running at all, so I think this is quite safe.

Wait for all filesystems to be available before starting docker (on upstart)

---

templates/default/upstart/docker.conf.erb

Found upstart service to fail on start due an lost "fi" from the "if" statement at the end of the script.

fix obsolate "fi" at the end of post-start script

---

templates/default/upstart/docker.conf.erb

See issue https://github.com/someara/chef-docker/issues/545
This will fix the return code for the Upstart job if already running.
Please test with Docker v1.8.3 as I don't have access to a box with it immediately.
cc @someara for review :smile:
PS: Your work is much appreciated as always #hugops

Chef fails if docker v1.9.x service already started

---

.gitignore
libraries/docker_service_base.rb
libraries/helpers_service.rb

Add support for --exec-opt to docker daemon.
This seems to be needed to workaround docker/docker#17653 on Centos 7.

Add support for --exec-opt to docker daemon

---

libraries/helpers_service.rb

Noticed that the naming of the `--cluster-store-opt` was wrong, a `s` to much.
From `docker daemon --help`
```
--cluster-store-opt=map[]            Set cluster store options
```

Rename cluster-opts to cluster-opt

---

libraries/docker_container.rb
libraries/helpers_base.rb

this should resolve #572 and #542.
now that the nil values are removed, `validate_container_create` can be expanded upon.

remove nil values from container create hash

---

libraries/helpers_base.rb

somewhere between switching to using our own connection and the latest docker-api gem, this is simply resolved by passing symbols instead of strings. timeout test-kitchen passes with flying colors.
the more you know :stars: 
resolves #458

excon opts should be symbols

---

libraries/helpers_installation_package.rb

Linuxmint is used on many Linux desktop installations. Linux Mint 17.X is based on the current Ubuntu LTS 14.04 trusty.

Support linuxmint 17.*, its based on trusty

---

libraries/docker_service_manager_execute.rb

Otherwise you might get `NoMethodError: undefined method `pid_file' for Chef::Resource::Execute`

Typo fix: it should be pidfile property

---

libraries/_autoload.rb

Handles these cases better:
1. If docker-api is not loaded or installed on the system, the cookbook’s version will be used.
2. If docker-api is not loaded, and docker-api 1.30 is installed on the system, that will be loaded instead.
3. If docker-api is not loaded, and docker-api 1.23 is installed on the system, the cookbook's version (1.24) will be used.
4. If someone else loaded docker-api 1.23 already, we fail to load the cookbook since it's not an acceptable version.
5. If someone else loaded docker-api 1.30 already, we don't load anything because it is an acceptable version.

Allow distributed gems to be activated normally via Ruby

---

README.md
libraries/docker_container.rb
libraries/helpers_container.rb
spec/docker_test/container_spec.rb
test/cookbooks/docker_test/recipes/container.rb
test/integration/resources-162/serverspec/assert_functioning_spec.rb
test/integration/resources-171/serverspec/assert_functioning_spec.rb
test/integration/resources-183/serverspec/assert_functioning_spec.rb
test/integration/resources-191/serverspec/assert_functioning_spec.rb

with great pleasure i bring you this fantastic, over the top, (some say) majestic, PR that resolves #493

parse binds to match docker cli parsing of -v

---

libraries/docker_service_base.rb

fixing #593: changed validation of docker_service's bridge attribute to String (as this is not an ip, but a existing network bridge name)

changed docker_service.bridge validation to be String

---

libraries/docker_service_manager_systemd.rb
templates/default/systemd/docker-wait-ready.erb

**VERSION**
2.4.0
Commit 052f747e8c0f69b177137d698226228f2885d093
**REPRODUCE**
( Edited after @bflad 's comment)
Use this modified docker-wait-ready.erb file to test failure
```
#!/usr/bin/env bash
i=0
while [ $i -lt <%= @service_timeout * 2 %> ]; do
<%= @docker_cmd %> ps | head -n 1 | grep ^failureCONTAINER > /dev/null 2>&1
[ $? -eq 0 ] && break
((i++))
sleep 0.5
done
[ $i -eq <%= @service_timeout * 2 %> ] && exit 1
exit 0
```

Fix #598. return value check for docker-wait-ready with systemd

---

libraries/docker_service_manager_execute.rb

**VERSION**
2.4.0
Commit 052f747e8c0f69b177137d698226228f2885d093
**FIXES**
Last iteration suceedd status.
**REPRODUCE**
This is a modified version of the script that waits 5 seconds instead of 20, and succeeds only in the last iteration.
```
timeout=0
while [ $timeout -lt 5 ];  do
docker ps | head -n 1 | grep ^CONTAINER && [[ $timeout -eq 4 ]]
if [ $? -eq 0 ]; then
break
fi
((timeout++))
sleep 1
done
[[ $timeout -eq 5 ]] && exit 1
exit 0
```
Exit code must be 0 if docker daemon is running and configured for default socket file.
Current behaviour for that same simulation is as follows
```
timeout=0
while [ $timeout -lt 5 ];  do
((timeout++))
docker ps | head -n 1 | grep ^CONTAINER && [[ $timeout -eq 5 ]]
if [ $? -eq 0 ]; then
break
fi
sleep 1
done
[[ $timeout -eq 5 ]] && exit 1
exit 0
``` …

Daemon execution fix for last iteration. Fixes #600

---

libraries/docker_container.rb
libraries/helpers_base.rb
libraries/helpers_container.rb
spec/docker_test/container_spec.rb
test/cookbooks/docker_test/recipes/container.rb
test/integration/resources-191/serverspec/assert_functioning_spec.rb

i think this should help resolve #597. compact was clobbering empty settings, which apparently can be important in certain cases.

setting container property defaults to match docker cli

---

libraries/helpers_container.rb

This PR fixes the problem I encountered with the recently released version 2.4.3 where my chef run would fail with the following exception:
```
Chef::Exceptions::ImmutableAttributeModification
------------------------------------------------
Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
Cookbook Trace:
---------------
/var/chef/cache/cookbooks/docker/libraries/helpers_container.rb:48:in `coerce_volumes'
...
```
This would trigger for docker_container resource where the volume/binds declaration is using the Array form (eg. `mycontainer.volume = ['/hostpath:/containerpath']`).

Fix coerce_volumes in case current value is a Chef::Node::ImmutableArray

---

libraries/helpers_service.rb

The current 'master' code is not working for docker >= 1.10
Explanation:
``` ruby
"1.10".to_f < 1.8
```
It results in running `docker -d` instead of `docker daemon`
This patch fix that by using `Gem::Version` class which handle pretty well versions, and even, pre-version.

Use Gem::Version to handle semantic verisoning and be compatible for ≥ 1.10

---

libraries/docker_network.rb

It seems that `host` property got removed from `Docker::Network` ( chef-cookbooks/docker@b743e8b609c9fd809399e19d2f4e164a24226e22 ). This makes it impossible to make a connection to the docker daemon ( https://github.com/chef-cookbooks/docker/blob/master/libraries/helpers_base.rb#L50 ). This PR will add `host` back so `docker_network` starts working again.
PS. I have tests for docker network on their way. DS.

Add host back to docker network

---

libraries/docker_container.rb

Isolated this bit from issue #597 and proposing a PR to fix the 'exposed_ports' case.
Currently using version 2.4.11 of this cookbook.
I have a docker_container on which redeploys at each chef-run. This container is using the `gliderlabs/registrator:v6` image, an image which does NOT expose any port all all, as shown by the following `docker inspect` commands:
```sh
$ docker inspect -f '{{ .Config.ExposedPorts }}' gliderlabs/registrator:v6
map[]
$ docker inspect -f '{{ .Config.ExposedPorts }}' phusion/passenger-ruby22:0.9.17
map[443/tcp:{} 80/tcp:{}]
```
At each chef-run, that docker_container is redeployed with the following trace:
* docker_container[registrator] action run
- stopping registrator 
- deleting registrator
- update registrator
-   set exposed_ports to {} (was nil)
- …

Set default docker_container.exposed_port to empty Hash

---

libraries/matchers.rb

This PR adds `ChefSpec.define_matcher` for each docker resource.
Currently in ChefSpec if I try to do something like
```ruby
resource = chef_run.docker_container('default')
expect(resource.env).to eq 'TEST=123'
```
I get
```
Failure/Error: resource = chef_run.docker_container('default')
NoMethodError:
undefined method `docker_container' for #<ChefSpec::ServerRunner:0x007faf52ece3f8>
```

Add ChefSpec.define_matcher for each docker resource

---

libraries/docker_service.rb

WARN: Default value nil is invalid for property package_options of resource docker_installation_package. Possible fixes: 
1. Remove 'default: nil' if nil means 'undefined'. 
2. Set a valid default value if there is a reasonable one. 
3. Allow nil as a valid value of your property (for example, 'property :package_options, [ String, nil ], default: nil'). 
Error: Property package_options must be one of: String!  You passed nil. at [...]/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'

Fix chef warning

---

templates/default/default/docker.erb

The template for /etc/default/docker was missing the option for rendering the no_proxy environment variable.  I've added the option after the http_proxy and https_proxy options.

Added no_proxy to default docker template

---

README.md

Per https://github.com/docker/docker/issues/18894 and https://github.com/docker/docker/pull/18902 setting memory_swap to -1 does not disable swap, but instead disables the swap limit.  This change brings the README wording inline with the upstream wording changes in https://github.com/docker/docker/pull/18902.

Note that -1 disables the swap limit, not swap itself

---

libraries/docker_container.rb
libraries/helpers_container.rb
metadata.rb

This PR:
- Ensures that wait_running_state uses the current state of the container, not a stored value, as discussed in #510 
- Throws an exception if wait_running_state times out.  This is used to allow retries for the second race mentioned in #679 and should cause test errors if the operation is timing out.
- Retries the stop operation if the container fails to stop in wait_running_state.  This resolves a difficult to reproduce corner case race mentioned in #679.

Resolve restarting container races

---

Gemfile
libraries/helpers_container.rb
spec/helpers_container_spec.rb

This PR fixes incorrect parsing of the `docker_container.image` property when the value looks like this: `repo:1337/blah:3.1`. It also adds full specs for the helper method that parses the value of `docker_container.image`.
The long story: when testing my wrapper cookbook, I found out that all my images were being redeployed at each chef-run with the following trace:
```
* docker_container[my-test-app] action run
- stopping my-test-app 
- deleting my-test-app
- update my-test-app
-   set repo to "10.0.2.2:2000/sample-docker-app" (was "10.0.2.2")   # <<<-- bug
-   set tag  to "latest" (was "2000/sample-docker-app:latest")  # <<<-- bug
- starting my-test-app
```
The reason was that I used a private repository with a custom port and that it messed up the way the docker_container#image …

Add support for docker_container image property with custom repository port.

---

libraries/docker_image.rb
libraries/helpers_image.rb

Implements load action for images
Requires [docker-api v1.27](https://github.com/swipely/docker-api/releases/tag/v1.27.0)

Image load

---

README.md

Fix the documentation to update the default signal for `docker_container` to `SIGTERM`, which appears to be the resource default here:
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_container.rb#L76
Resolves an inconsistency between the code and documentation.

Minor README.md fix

---

.gitignore
.kitchen.cloud.yml
.kitchen.yml
.travis.yml
Berksfile
README.md
Rakefile

Use chef-apt-docker for testing
Wraps up Ubuntu 16.04 support

Use chef-apt-docker for testing

---

.kitchen.cloud.yml
.kitchen.yml
Berksfile
README.md
libraries/docker_container.rb
libraries/helpers_base.rb
libraries/helpers_installation_package.rb

Remove the Fedora 21 specific support and instead use generic Fedora support. Also use the latest version on Fedora since 1.9 doesn't even exist there.
[List any existing issues this PR resolves]

Fedora 22/23 support

---

README.md
libraries/docker_service_base.rb
libraries/helpers_service.rb
metadata.rb

Adds the ability to configure the --userns-remap= daemon namepace option by setting the userns_remap parameter to the docker_service resource 
Fixes issue 714 submitted by myself.
- [x ] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x ] New functionality includes testing.
- [x ] New functionality has been documented in the README if applicable
- [x ] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

DOCKER-714 added ability to configure namespace for daemon option

---

libraries/_autoload.rb

Avoid forcing cookbooks directly or indirectly depends on "docker" cookbook to install docker-api gem when they run chefspec.
Currently docker cookbook forces every single cookbook which directly or
indirectly depends on docker cookbook to install docker-api when they run
their chefspec or to stub-out installation of the gem.
It should have been unnecessary unless those chefspecs step into recipes
defined in docker cookbook.
This commit avoid installing docker-api when this cookbook is loaded as
a part of chefspec.
Without this change, chefspec in dependent cookbooks would have errors
like this.
```console
Failure/Error: runner.converge(described_recipe)
NoMethodError:
undefined method `step_into?' for nil:NilClass
```
- [N/A] New functionality includes testing.
- [N/A] New functionality …

Avoid installing docker-api gem in ChefSpec

---

.kitchen.yml
README.md
libraries/docker_installation_tarball.rb
libraries/helpers_installation_tarball.rb
test/cookbooks/docker_test/recipes/installation_tarball.rb
test/integration/installation_tarball-1111/inspec/assert_functioning_spec.rb

The binary installation method in Docker 1.10.0 onwards changed [1].
The old one is still compatible up to 1.10.+ but doesn't work with
1.11.0 onwards.
This new resource accomodates this method. I think adding a new resource
is better rather than complicating the logic in the existingh
docker_installation_binary resource.
[1] https://docs.docker.com/engine/installation/binaries/#install-the-linux-binaries
None

Install Docker 1.11.0+ using tarballs

---

Gemfile
README.md
libraries/docker_container.rb
spec/docker_test/container_spec.rb
test/cookbooks/docker_test/recipes/container.rb
test/integration/resources-1100/inspec/assert_functioning_spec.rb
test/integration/resources-1112/inspec/assert_functioning_spec.rb
test/integration/resources-162/inspec/assert_functioning_spec.rb
test/integration/resources-171/inspec/assert_functioning_spec.rb
test/integration/resources-183/inspec/assert_functioning_spec.rb
test/integration/resources-191/inspec/assert_functioning_spec.rb

Add uts_mode support for docker_container provider. 
https://docs.docker.com/engine/reference/run/#/uts-settings-uts here is option description.
> UTS settings (--uts)
> --uts=""  : Set the UTS namespace mode for the container,
>        'host': use the host's UTS namespace inside the container
> The UTS namespace is for setting the hostname and the domain that is visible to running processes in that namespace. By default, all containers, including those with --network=host, have their own UTS namespace. The host setting will result in the container using the same UTS namespace as the host. Note that --hostname is invalid in host UTS mode.
>You may wish to share the UTS namespace with the host if you would like the hostname of the container to change as the hostname of the host changes. A …

Add uts_mode support for docker_container provider

---

Gemfile
README.md
libraries/docker_service_base.rb
libraries/helpers_service.rb

I am using this cookbook with flannel. Flannel creates a docker bridge, and exposes the docker bip subnet through an env file. I can override the systemd environmentFile option through using the docker-instance.d/ conf file easily.
However, to pass the environment variable in the env file to the docker daemon, i need to evaluate the var at runtime, by setting something like this ```--bip=${FLANNEL_SUBNET}``` at docker daemon runtime.
Therefore I need to set the bip property of the docker_service provider to ```${FLANNEL_SUBNET}```, however it fails IP address validation against the regex in the provider, understandably.
Therefore, we should be able to pass arguments as strings to avoid validation in these edgecases.
None.

Add extra options to daemon

---

libraries/helpers_service.rb

Add logic to use the dockerd binary on docker 1.12+. Init scripts still need to be updated as some `/usr/bin/docker` invocations are hardwired.
None

Switch to the dockerd binary on 1.12+

---

libraries/docker_service_manager_upstart.rb
libraries/helpers_service.rb
templates/default/default/docker.erb

Starting from Docker 1.12 /usr/bin/dockerd should be used instead of /usr/bin/docker in Upstart init script.
Fix for issue with starting Docker 1.12+ using Upstart.

Dockerd binary on 1.12+ for Upstart

---

.kitchen.yml
libraries/docker_service.rb
metadata.rb
test/cookbooks/docker_test/recipes/service_install_tarball.rb
test/integration/service_install_tarball-1111/inspec/assert_functioning_spec.rb

Docker versions > 0.11 don't support binary installation, so tarball
installation must be used instead.
This change ensures you can use `docker_service` as a single action
to install via tarball, as previously this was missed.
-
- [n/a] New functionality has been documented in the README if applicable

Enable tarball install through docker_service

---

README.md
libraries/docker_service_base.rb
libraries/docker_service_manager_systemd.rb
libraries/helpers_service.rb
templates/default/systemd/docker.service-override.erb

Modifies the template file and systemd service files to allow users to specify an array of Systemd options, such as "TasksMax=infinity" that need to go into the /etc/systemd/system/docker.service file.
Pull request #759 and associated issue #756 would be covered by this in that rather than assuming a default for MountFlags that would need to apply to all Docker service deployments in Chef, users could dictate these settings through an attribute/property of the docker_service resource or docker_service_manager resource without losing the other extremely useful features of the cookbook by having to rewrite that file with their own cookbooks.
It's not really right to assume that MountFlags will be the very last setting that developers will want to change in the systemd settings--the list of …

Enable systemd options as a docker_service attribute.

---

libraries/docker_container.rb

This commit adds ReadonlyRootfs to the list of keys which are skipped in the automated load of state and then maps ro_rootfs to the ReadonlyRootfs manually as was done with other similar cases.
The ro_rootfs property of the docker_container resource doesn't match the property in the docker HostConfig (called ReadonlyRootfs).
As a result, chef fails to properly load the value into the state of the current resource and forces a redeploy even when no change has been made.
to prevent redeploying containers with ro_rootfs = true
Signed-off-by: Yonah Russ <me@yonahruss.com>

Added ro_rootfs => ReadonlyRootfs special cases mapping

---

libraries/docker_service_manager_sysvinit_debian.rb

`docker_daemon` variable has been added to `templates/default/default/docker.erb` in #741, which is used by `docker_service_manager_sysvinit_debian` and `docker_service_manager_upstart` resources.
Only Upstart resource has been updated in said PR, breaking sysvinit Debian setups.
Signed-off-by: Jonathan Amiez jonathan.amiez@gmail.com

Fix regression introduced by #741, breaking Debian install

---

README.md

Fixes to README file
incorrect default action
Default action for docker_container is :run
and not :run_if_missing.

Updating README upon code changes

---

libraries/helpers_image.rb

When try to pull a container from private dockerhub we are receiving the follow message:
`Docker::Error::NotFoundError
----------------------------
No such image: arizona/carrefour-web-view-nginx:develop`
The bug:
The method are receiving credentials create a header with creds data to call dockerhub api. This headers is a composition of username, password and email, but the cookbook is passing serverAddress and the header goes broken.
Non-Ok creds:
`creds = {"serveraddress"=>"index.docker.io", "username"=>"XXX", "password"=>"XXX", "email"=>"XXX"}
`
Ok creds:
`creds = {"username"=>"XXX", "password"=>"XXX", "email"=>"XXX"}
`
No issues reported

Fix pull from private dockerhub repository

---

libraries/docker_container.rb

Docker versions starting from v1.12 support setting of dns options and they are not mutually exclusive with **host network_mode**.

Fixed dns options mutual exclusion

---

libraries/docker_service_manager_execute.rb

I've only been able to reproduce this when doing Docker-in-Docker via
kitchen-docker, but there are cases where the restart can happen faster
than Docker can stop. There is a split second after killing the process
where the PID file still exists, and Docker will fail to start if the
PID file exists.
Signed-off-by: Jonathan Hartman <j@p4nt5.com>

When stopping via execute, wait until Docker is fully stopped

---

metadata.rb

Avoid a pile of pain with compat_resource

Require 12.5 and remove the need for compat_resource

---

README.md

Change the mention of `syslog-tag` to `tag` in the README.
No existing issues, though https://github.com/Accenture/adop-docker-compose/issues/115 is revelant.
I hate to be even putting in this PR for a one-word change, but it was a bit of a search before I figured out this was the issue. The related (but closed) issue is eight months old, so maybe the assumption of users running a newer docker version is safe?

Update syslog-tag mention in README.md

---

README.md
libraries/docker_service.rb

When installing docker using a `package` value for the `install_method` attribute, the default package name `docker-engine` could not be altered and was incorrect for the Centos platform. Based on step 2 of [the centos install process](https://docs.docker.com/engine/installation/linux/centos/#install-docker-1) the `package_name` should be either `docker-ce` for community edition or `docker-ee` for the enterprise edition.
The PR does not attempt to alter existing functionality, only to expose the ability to customize the `package_name` property from the `docker_service` resource.
None.

Expose package_name through the docker_service resource

---

README.md
libraries/docker_container.rb

Docker host_name actually doesn't set containers' hostname globally to
the docker network. But `--network-alias` does.

Add network_aliases support

---

libraries/docker_service_manager_upstart.rb
libraries/helpers_service.rb
templates/default/upstart/docker.conf.erb

The upstart config in this cookbook includes the daemon argument `--raw-logs`, which is only valid in docker-engine versions after [1.11.0](https://github.com/moby/moby/blob/89658be/CHANGELOG.md#logging-6), however the argument is currently hard coded, breaking the docker daemon on any upstart using system running docker daemons prior to version 1.11.0.
This change adds a `docker_raw_logs_arg` helper which enables or disables the raw-logs argument depending on the version used. This changeset updates the upstart template to make use of the `docker_raw_logs_arg` helper.
https://github.com/chef-cookbooks/docker/issues/839
---
Regarding testing: I'm unfamiliar with kitchen and InSpec. Can I get some guidance on where to add tests here? Is testing for older versions of docker even required?

Only use --raw-logs argument in versions which support it

---

libraries/docker_container.rb

I was getting read timeout errors when using the :restart action on multiple docker_container resources in the same run.
```
Docker::Error::TimeoutError
---------------------------
read timeout reached
Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:396:in `block (2 levels) in \<class:DockerContainer\>'
```
Noticed that the default value of the 'kill_after' property on the docker_container resource was '-1'.    When looking at the docker-api gem code (https://github.com/swipely/docker-api/blob/v1.33.1/lib/docker/container.rb#L229-L235) saw that this would now force set 'read_timeout' and 'write_timeout' to 4 seconds.   Looks like 'nil' would be the proper default value to use for the documented default behavior of never killing the …

Bug: Change kill_after property default value to nil

---

libraries/docker_service_manager_systemd.rb
test/cookbooks/docker_test/recipes/smoke.rb

Adds a systemctl restart resource so that changes in docker_service properties restarts the service. 
#849

Add systemctl restart resource and appropriate notifications.

---

README.md
libraries/docker_network.rb
libraries/helpers_network.rb
spec/docker_test/network_spec.rb
test/cookbooks/docker_test/recipes/network.rb
test/integration/network/inspec/assert_functioning_spec.rb

allow setting the [EnableIPv6](https://docs.docker.com/engine/api/v1.30/#operation/NetworkCreate) option to create networks with IPv6 support.

docker_network: support ipv6

---

libraries/helpers_container.rb
test/cookbooks/docker_test/recipes/container.rb

regex in https://github.com/chef-cookbooks/docker/blob/ebfbb1598bfc45dff8c6ec025893d22a9633cef3/libraries/helpers_container.rb#L21 is broken and only splits lower-case characters.

fix to_bytes parsing

---

libraries/docker_service_manager_upstart.rb

When changing a /etc/init/<service>.conf file, restart won't get the new config.
Only running stop, and then start will get the latest config from disk.
http://upstart.ubuntu.com/cookbook/#restart

Stop and start upstart service instead of restarting

---

README.md

Removes a duplicate description for an option in service. README change only

Remove duplicate `labels` description in README

---

README.md
libraries/helpers_installation_package.rb

There's no excuse to be running a non-LTS EOL distro at this point.

Remove support for EOL non-LTS Ubuntu distros

---

.kitchen.yml
libraries/helpers_installation_package.rb
test/integration/installation_package-17032/inspec/assert_functioning_spec.rb

Package `docker-17.03.2ce-1.59.amzn1` is available on Amazon Linux from the amzn-updates repository but the cookbook is still defaulting to `docker-17.03.1ce-1.50.amzn1`.
This PR attempts to update the default package version installed on Amazon Linux.
#921

Update Amazon Linux to default to 17.03.2

---

.kitchen.yml
libraries/helpers_installation_package.rb
test/integration/installation_package-17062/inspec/assert_functioning_spec.rb

Package `docker-17.06.2ce-1.93.amzn1` is available on Amazon Linux from the amzn-updates repository but the cookbook is still defaulting to `docker-17.03.2ce-1.59.amzn1`.
This PR attempts to update the default package version installed on Amazon Linux.
#938

Update Amazon Linux to default to 17.06.2

---

libraries/helpers_installation_package.rb

Package `docker-17.06.2ce-1.94.amzn1` is available on Amazon Linux from the amzn-updates repository but the cookbook is still defaulting to `docker-17.06.2ce-1.93.amzn1`.
This PR attempts to update the default package version installed on Amazon Linux.
#945

Update Amazon Linux package to 17.06.2ce-1.94.amzn1

---

libraries/helpers_installation_binary.rb

1.11 is actually EOL. 1.10.2 which I've left behind is also EOL, but 1.6 is EOL beyond EOL. Let it die.

Remove support for EOL beyond EOL distros in the binary install resource

---

libraries/docker_service_manager_execute.rb
libraries/docker_service_manager_systemd.rb
libraries/docker_service_manager_sysvinit_debian.rb
libraries/docker_service_manager_upstart.rb
libraries/helpers_installation_package.rb

Precise has been EOL since April and the provides logic can be both simplified and expanded to support addition distros.

Simplify resource provides and remove support for Ubuntu Precise

---

libraries/docker_network.rb

Signed-off-by: Matt Kulka <mkulka@parchment.com>
These attributes currently default to nil every time the resource is loaded during each Chef run causing an attempt to destroy and recreate the network. This will load the state for these attributes from the Docker API response.
Fix #951

load internal and ipv6 status for existing docker_network resources

---

.kitchen.yml
libraries/helpers_installation_package.rb
test/integration/installation_package-17091/inspec/assert_functioning_spec.rb

Package `docker-17.09.1ce-1.111.amzn1` is available on Amazon Linux from the amzn-updates repository but the cookbook is still defaulting to `docker-17.06.2ce-1.94.amzn1`.
This PR attempts to update the default package version installed on Amazon Linux.
Thank you very much for your patience :-)
#960

Update Amazon Linux package to docker-17.09.1ce-1.111.amzn1

---

README.md
libraries/docker_container.rb

Adds ability to set `runtime` argument when running a container (ie. [https://hackernoon.com/docker-containerd-standalone-runtimes-heres-what-you-should-know-b834ef155426](https://hackernoon.com/docker-containerd-standalone-runtimes-heres-what-you-should-know-b834ef155426))
No issues resolved... only a feature addition.

Adding 'runtime' config option to 'docker_container'.

---

libraries/helpers_base.rb

This code change resolves a label parsing issue when the value of the label contains colons.
Refer to Issue 965 for further details.
https://github.com/chef-cookbooks/docker/issues/965

coerce_labels change to address issue #965

---

libraries/docker_registry.rb

This PR adds the sensitive flag to the password property of the docker_registry resource, so the password doesn't show up in logs or on stdout.

Flag registry password property as sensitive in docker_registry resource

---

README.md
libraries/docker_container.rb
test/cookbooks/docker_test/recipes/container.rb
test/integration/resources/inspec/assert_functioning_spec.rb

Added **oom_kill_disable** and **oom_score_adj** support to docker_container.
https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources
https://docs.docker.com/config/containers/resource_constraints/#memory

Added oom_kill_disable and oom_score_adj support to docker_container

---

spec/docker_test/container_spec.rb
spec/docker_test/exec_spec.rb

commands and entrypoints are interpreted as arrays
fixes all the broken unit tests under the UNIT_AND_LINT=1 section of tests on travis-ci
container commands and entrypoints are interpreted as arrays
unit test changes ONLY
- [X ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [X ] New functionality includes testing.

fix for specs ONLY

---

.travis.yml
kitchen.yml
libraries/docker_installation_package.rb
libraries/docker_installation_tarball.rb
spec/docker_test/installation_package_spec.rb
test/cookbooks/docker_test/recipes/installation_package.rb
test/integration/installation_package/inspec/assert_functioning_spec.rb
test/integration/installation_tarball/inspec/assert_functioning_spec.rb
test/integration/resources/inspec/assert_functioning_spec.rb

docker-ce has an updated versioning scheme
xenial is ```18.03.1~ce-0~ubuntu```, bionic is ```18.03.1~ce~3-0~ubuntu```
See - https://github.com/docker/docker-ce-packaging/pull/91
See - https://github.com/seemethere/docker-ce-packaging/blob/9ba8e36e8588ea75209d813558c8065844c953a0/deb/gen-deb-ver#L16-L20
Also bump the default version from 18.03.0 to 18.03.1 which is the first official package with bionic support.
This enables ubuntu bionic to be able to install docker-ce
It currently can't find the correct package from the official docker repository
- [X ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [X ] All commits have been …

Use new package versioning scheme for bionic

---

libraries/docker_service_base.rb

provides a fix to set :log_level for dockers' syslog driver.
#999

 #999: docker service :log_level property converted to String.

---

libraries/docker_container.rb
spec/docker_test/container_spec.rb
test/cookbooks/docker_test/recipes/container.rb
test/integration/resources/inspec/assert_functioning_spec.rb

A `docker_container` resource with `detach(true)` will fail on Chef 14. The container wait stuff isn't specifying `new_resource` or `current_resource` and gets the following error:
```
    ArgumentError
    -------------
    wrong number of arguments (given 0, expected 1..3)
    
    Cookbook Trace:
    ---------------
    /opt/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:562:in `block (3 levels) in <class:DockerContainer>'
    /opt/kitchen/cache/cookbooks/docker/libraries/docker_base.rb:29:in `with_retries'
    /opt/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:555:in `block (2 levels) in <class:DockerContainer>'
    /opt/kitchen/cache/cookbooks/docker/libraries/docker_container.rb:554:in `block in <class:DockerContainer>'
    …
```

docker_container detach=false

---

README.md

The example shows the correct resource name, but the prose says the name is `docker_execute`

docker_execute -> docker_exec in README.md

---

libraries/docker_service_base.rb
libraries/helpers_service.rb
spec/docker_test/service_spec.rb
test/cookbooks/docker_test/recipes/service.rb

Prevents docker services from restarting when version 4.4.0 is deployed, and other fallout from that change.
docker_service log_level was defaulted from nil to 'info' as part of this PR:
https://github.com/chef-cookbooks/docker/pull/1000/files
The default should not be info, it should default to whatever the docker default is.
Ex. What is defined here if you run the daemon without specifying the option -
https://docs.docker.com/engine/reference/commandline/dockerd/
The net-effect of setting the default from nil to info is that the systemd system unit gets updated 
FROM
ExecStart=/usr/bin/dockerd  --bip=10.10.10.0/16 --group=docker --pidfile=/var/run/docker.pid --storage-driver=overlay2
TO
ExecStart=/usr/bin/dockerd  --bip=10.10.10.0/16 …

sets the default log_level for the systemd docker service back to nil

---

README.md
kitchen.yml
libraries/docker_plugin.rb
spec/docker_test/plugin_spec.rb
test/cookbooks/docker_test/recipes/plugin.rb

Implement a ``docker_plugin`` resource which is used to manage [Docker Engine managed plugins](https://docs.docker.com/engine/extend/). This includes installation, enabling/disabling, (re-)configuring and removal of plugins.
* Fixes #942 
* Waiting for travis-ci results on the "All tests pass" front :)
* I’m not entirely sure how to test this better. There are some smoke-testy-tests in `plugins.rb` + corresponding spec tests in the test cookbook, but I’m not 100% happy with it yet. I’m open to suggestions on how to improve this. I only found the two plugins listed (many other plugins are available, but not as Docker Engine managed ones), and both depend on external resources (an ssh server or a Ceph cluster), so creating volumes using those plugins doesn’t seem viable.
* As mentioned in …

Implement docker_plugin resource

---

spec/docker_test/plugin_spec.rb
test/cookbooks/docker_test/recipes/plugin.rb

Obvious fix.
Use the correct tag for the vieux/sshfs plugin in the tests.
- [N/A] New functionality includes testing.
- [N/A] New functionality has been documented in the README if applicable
- [N/A] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>
* Fixes test breakage due to #1020.

Use correct remote tag to fix tests

---

README.md
libraries/docker_volume.rb

The `driver` and `opts` properties of the `docker_volume` resource were not used at all, despite their existence being documented in the README. This PR fixes this by passing the properties to the `Docker` call and documenting what they do and when they’re used.
None
* I haven’t written tests for this. I have no idea how to do this. I could write something like:
```ruby
docker_volume 'foo' do
driver 'local'
action :create
end
```
but that would not test anything useful, since ``local`` is the default on the Docker side of things, so not passing it and passing ``local`` has the same effect. A "good" way to test this would be with a separate volume driver, however, all drivers I know of require provisioning of an external resource (e.g. sshfs or ceph).
However, I was able to create a …

Fix passing of driver and opts to Docker::Volume.create

---

libraries/docker_installation_package.rb

After the new debian package version generation, the ubuntu and debian
packages in repositories follow the new convention after docker version
18.03.
This commit adds two more return cases in the package installation
method that computes the version to consider the new naming convention
in docker packages.
This is basically fixes the new naming for packages for debian and ubuntu platforms, as #1024 did for centos.

Use different version string on .deb packages

---

CHANGELOG.md
README.md
libraries/docker_service_base.rb
libraries/helpers_service.rb
metadata.rb
spec/docker_test/service_spec.rb
test/cookbooks/docker_test/recipes/service.rb

Added support for the new `default-ip-address-pool` daemon parameter.
-

Added default-ip-address-pool daemon option

---

libraries/docker_installation_package.rb

When installing docker via package on debian platforms, fetch via httsp the latest gpg public key server from download.docker.com
Help avoiding keyserver unavailability transient errors, that is one of the most common transient network errors during first converge.

Import docker repository gpg key from http

---

libraries/docker_container.rb

Fixes ```NameError: undefined local variable or method `container' for #<#<Class:0x00000000058b9c50>:0x0000000005686b18>``` when attempting to reload a container. 
n/a
[n/a] New functionality includes testing.
[n/a] New functionality has been documented in the README if applicable
[n/a] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

add missing object to reload

---

libraries/docker_installation_package.rb
spec/docker_test/installation_package_spec.rb

Did not realize that the epoch is set for 18.09 and required for installation to work properly.
The package can't be installed without specifying the epoch.
See docker-ce 18.09 in
https://download.docker.com/linux/ubuntu/dists/bionic/stable/binary-amd64/Packages
```
Package: docker-ce
Architecture: amd64
Version: 5:18.09.0~3-0~ubuntu-bionic
```
Fixes https://github.com/chef-cookbooks/docker/pull/1040
- [X ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

18.09 - add epoch to version string

---

README.md
libraries/docker_container.rb
spec/docker_test/container_spec.rb
test/cookbooks/docker_test/recipes/container.rb

Allows health_check to be used for containers
https://docs.docker.com/engine/reference/run/#healthcheck
https://docs.docker.com/engine/api/v1.39/#operation/ContainerCreate
https://github.com/chef-cookbooks/docker/issues/974
- [ X] New functionality has been documented in the README if applicable

Add support for container health_check options

---

libraries/docker_container.rb
spec/libraries/container_spec.rb

Fix broken issues with existing network_mode implementation which will allow it to be functional.  
Should not break any existing functionality as this is not even called with the existing schema/api version of the docker api gem.
This only gets called when API is 1.21 or greater.  Unless you are overriding the api schema version or using a pre-release version of the docker-api gem this should have no impact.
(There is a blurb about this in the issue.)
It will be good to fix this now as they are preparing version 2.X of the docker api gem.
See - https://github.com/swipely/docker-api/tree/release-2.x
Once this 2.X gem is released and used, this cookbook may break without this change.
https://github.com/chef-cookbooks/docker/issues/998
- [ X] All tests pass. See …

fix issues with network_mode

---

libraries/docker_registry.rb
spec/libraries/registry_spec.rb

Add 'host' property to docker_registry resource
host is required in docker_base
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_base.rb#L16
host is set in all other providers which inherit from DockerBase
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_image.rb#L11
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_network.rb#L11
https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_container.rb#L30
....etc
host is missing from docker_registry - this adds it.  As it initializes a default of `nil` net effect should be no change.
- [ X] New functionality …

docker_registry resource should have 'host' property

---

README.md
libraries/docker_container.rb
test/cookbooks/docker_test/recipes/container.rb
test/integration/resources/inspec/assert_functioning_spec.rb

This change enables setting the shared memory size of a container, as one would with `docker run --shm-size ...`.
This functionality was added in Docker 1.10.0 - this would break older Dockers. I do not know what level of compatibility this project attempts to maintain with Docker itself.
#1030

Support setting shared memory size.

---

libraries/docker_installation_package.rb

Currently yum and apt both have x86_64/amd64 set statically in their repository
URL's. Upstream currently supports at least aarch64 as well as armv7l on Debian.
I also included ppc64le just in case they add this later and fall back to
``node['kernel']['machine']`` if nothing is found.
[Describe what this change achieves]
[List any existing issues this PR resolves]

Include support for other architectures using upstream repo

---

libraries/docker_container.rb

This fixes the following error:
```
NameError
---------
undefined local variable or method `restart_policy' for #<#<Class:0x00000000054923c0>:0x0000000008167a80>
```

Use new_resource to read attribute

---

.travis.yml
README.md
kitchen.yml
spec/docker_test/installation_package_spec.rb

I've been using this recipe with Debian 10 without any issues. So I've configured the tests to run on debian 10, the same way they do for debian 9, and they all pass.

Verify debian 10 support

---

README.md
libraries/docker_service_base.rb
libraries/helpers_service.rb

Option `--live-restore` is for keeping containers alive during daemon downtime
Defaults to `false`
More information: https://docs.docker.com/config/containers/live-restore/

Add 'live_restore' property to 'docker_service'

---

libraries/docker_container.rb

I was getting a trace back when using the newest version of the cookbook on Chef 14 when trying to set a restart_policy for a container:
```
NameError
---------
undefined local variable or method `restart_policy' for #<#<Class:0x00000000042fe6e0>:0x0000000007337e88>
Cookbook Trace:
---------------
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:698:in `validate_container_create'
/var/chef/cache/cookbooks/docker/libraries/docker_container.rb:473:in `block in <class:DockerContainer>'
```
It looks like on line 698 of the docker_container definition, there was a missing new_resource when referencing the restart_policy property of the resource. This causes this property to not work on Chef 14 and higher as new_resource is now required
This pull request adds the missing …

Fix missing reference to new_resource.restart_policy

---

.travis.yml
README.md
kitchen.yml
libraries/docker_installation_package.rb
metadata.rb
spec/docker_test/installation_package_spec.rb
test/cookbooks/docker_test/recipes/installation_package.rb

Chef Infra Client 15 reworked how versions are handled and made it so we can do versions like 19.03.3*. This means we can take the version in from the user and just do the right thing without constantly updating fragile helpers that build the full version string. We sadly still have that logic for Debian/Ubuntu, but baby steps.

Require Chef Infra Client 15+ to fix issues with package versions

---

libraries/docker_container.rb
spec/docker_test/container_spec.rb

Container being redeployed after every chef-run.
- Removed default value for properties working_dir and memory_swap.
#1092

Container being redeployd fixes

---

libraries/docker_exec.rb
spec/docker_test/exec_spec.rb
spec/docker_test/installation_package_spec.rb
test/cookbooks/docker_test/recipes/exec.rb

Signed-off-by: Kapil Chouhan <kapil.chouhan@msystechnologies.com>
- `docker_exec` resource was not failing if the command fails, so we have fixed it.
- Added `returns` property
Fixes: #1081

Fix for docker_exec does not check the return code of the command it runs

---

libraries/docker_container.rb
libraries/docker_exec.rb
libraries/docker_image.rb
libraries/docker_image_prune.rb
libraries/docker_installation_package.rb
libraries/docker_installation_tarball.rb
libraries/docker_network.rb
libraries/docker_plugin.rb
libraries/docker_registry.rb
libraries/docker_service_manager_execute.rb
libraries/docker_tag.rb
libraries/docker_volume.rb

Reverts #1113
This broke Chef 15
```
Chef::Exceptions::InvalidResourceSpecification: [my_docker_registry].resource_name is `nil`!  Did you forget to put `provides :blah` or `resource_name :blah` in your resource class?
```
Source:
https://github.com/chef/chef/blob/2f78efa0f657c67ea1d8ec04b8fcd645f36d7c7e/lib/chef/resource_builder.rb#L47-L49
#1115

Revert #1113 for breaking backwards-compat for chef <16

---

README.md
libraries/docker_installation_package.rb

Signed-off-by: Corey Hemminger <hemminger@hotmail.com>
Adds the ability to install latest package version by not specifying package_version property or version property. Maintains backwards compatibility by still defaulting to old functionality if version is specified it'll calculate debain family package version properly and ensure system has that version installed or revert system back if newer package is found. 
- [x ] New functionality includes testing.
- [x ] New functionality has been documented in the README if applicable
- [x ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

added ability to upgrade package installations

---

CHANGELOG.md
libraries/helpers_service.rb
spec/docker_test/service_spec.rb

systemd typo for default-ip-address
The change corrects a typo in the systemd 
https://github.com/chef-cookbooks/docker/blob/master/libraries/helpers_service.rb
Line 205 is currently
opts << "--default-address-pool=#{default_ip_address_pool}" unless default_ip_address_pool.nil?
and needs to be
opts << "--default-address-pool #{default_ip_address_pool}" unless default_ip_address_pool.nil?
#1129 
- [N/A] New functionality includes testing.
- [N/A] New functionality has been documented in the README if applicable

#1129 - fix issue with default-ip-addr in systemd

---

CHANGELOG.md
libraries/docker_installation_tarball.rb

This guard prevents you from installing a newer or different version of the
tarball from one you had initially installed. Since the default action is set to
nothing and gets triggered from downloading a new tarball, this shouldn't be a
problem.

Remove creates guard for extracting tarball which prevents upgrades

---

CHANGELOG.md
README.md
libraries/docker_service_base.rb
libraries/helpers_service.rb
spec/docker_test/service_spec.rb
test/cookbooks/docker_test/recipes/service.rb

Updates the `registry_mirror` option of `docker_service` to users can provide either a single mirror or a list, solving #1144 
Solves #1144

GH-1144, update the registry_mirror option to allow multiple mirrors

---

CHANGELOG.md
libraries/docker_container.rb
libraries/docker_service_base.rb

This adds `local` as a supported value for the `log_driver` resource property for both `DockerContainer` and `DockerServiceBase` resources.
cf https://docs.docker.com/config/containers/logging/local/
#1125

Add `local` value to `log_driver` resource property

---

CHANGELOG.md
README.md
kitchen.yml
libraries/docker_installation_tarball.rb
spec/docker_test/installation_package_spec.rb
test/cookbooks/docker_test/recipes/installation_package.rb
test/cookbooks/docker_test/recipes/installation_tarball.rb
test/integration/installation_package/inspec/assert_functioning_spec.rb
test/integration/installation_tarball/inspec/assert_functioning_spec.rb
test/integration/resources/inspec/assert_functioning_spec.rb

Docker 20.10.x was released in December with the latest version being 20.10.1. This updates everything to start using and testing this release. This should fix test failures with the current branch.
In addition, update tarball for 19.03 to 19.03.14.

Update to use 20.10 by default

---

CHANGELOG.md
libraries/docker_container.rb

This PR adds in support for the loki-docker driver that can be installed via the docker plugin resource, line can also be adjusted to below to allow for any custom logging docker plugin
`property :log_driver, String, default: 'json-file'. desired_state: false`
#1124

Allowing for loki docker driver

---

CHANGELOG.md
libraries/docker_container.rb

Fixes that `reload_signal` and `cpus` made the container restart on every chef run if diffrent from the default value.
See comments in PR #1090

fixed reload_signal and cpus bug

---

CHANGELOG.md
README.md
libraries/docker_image.rb
test/cookbooks/docker_test/files/Dockerfile_5
test/cookbooks/docker_test/recipes/image.rb

Adds `buildargs` property to the `docker_image` resource.
The new property is supported in building from a Dockerfile, a directory, and a tarball.
#884

Add `buildargs` propety to the `docker_image` resource

---

CHANGELOG.md
libraries/docker_installation_package.rb
spec/docker_test/installation_package_spec.rb

Docker provides RPMs for s390x on RHEL but _not_ CentOS (since CentOS does not include an s390x build). This provides proper logic to handle the Yum repository correctly.
Additionally, update the ChefSpec tests for the `docker_installation_package` resource with the following:
- Use newer ChefSpec coding style
- Remove tests for Ubuntu 16.04 (EOL in April 2021)
- Add tests for Ubuntu 20.04
- Add tests for yum/apt repos
- Add tests for some edge cases using other non-x86 architectures
- Update docker version string tests to include 20.10

Fix package installation on RHEL s390x architecture

---

CHANGELOG.md
libraries/helpers_service.rb

At least on ppc64le, `docker --version` returns:
```
Docker version v20.10.7, build f0df350
```
Instead of the following on other platforms:
```
Docker version 20.10.7, build f0df350
```
This causes a problem when parsing with `Gem::Version` so this strips any `v` from the string.

Fix `installed_docker_version` method on ppc64le which appends `v` to the version

---

CHANGELOG.md
libraries/docker_image.rb
spec/spec_helper.rb

`docker_image :load` is not idempotent in its current form; adding a `return if` in the same vein as `:import`
Ensure `docker_image :load` is idempotent

docker_image :load is not idempotent without a "return if"

---

.github/workflows/ci.yml
CHANGELOG.md
kitchen.yml

This should fix tests that are currently failing.

Disable installation-script-main suite on Debian 9 due to lack of upstream support

---

CHANGELOG.md
resources/network.rb

- Adds unifed_mode
- Allows us to remove the Library inheriting from Chef Resource and instead rely on the Custom Resource magic to do the heavy lifting
NA

Move the docker_network library to a custom resource

---

CHANGELOG.md
resources/exec.rb

docker_exec is currently failing following the move from a library to resource due to not using partial/_base
I opened this instead of opening an issue ;)

update exec resource to use partial/_base

---

CHANGELOG.md
libraries/docker_installation_tarball.rb

Adding the property `append true` is required to not reset members within
docker group at each converge.
- #1205

Fix group resource for `docker_installation_tarball` library in #1205

---

CHANGELOG.md
README.md
kitchen.yml
libraries/docker_installation_tarball.rb
spec/docker_test/installation_package_spec.rb
test/cookbooks/docker_test/recipes/installation_package.rb
test/cookbooks/docker_test/recipes/installation_tarball.rb
test/integration/installation_tarball/inspec/assert_functioning_spec.rb
test/integration/resources/inspec/assert_functioning_spec.rb

Also update to using version 20.10.11 for testing suites. This is needed for #1208 to pass properly.

Update to tarball checksums to 20.10.11 and 19.03.15

---

CHANGELOG.md
resources/network.rb

- Fix raise when using mixed address families with a network
- n/a

Fix raise when using mixed address families with a network

---

CHANGELOG.md
libraries/helpers_json.rb

Fix generate_json not accepting a variable number of arguments
- n/a

Fix generate_json not accepting a variable number of arguments

---

CHANGELOG.md
resources/container.rb

Sort container volume_binds to prevent containers being re-deployed erroneously as docker may return the volume_binds in a different order to how they are specified as a resource property.
- n/a

Sort container volume_binds

---

CHANGELOG.md
resources/image_prune.rb

Signed-off-by: Hans Rakers <h.rakers@global.leaseweb.com>
This PR fixes the arguments passed to `generate_json` in the docker_image_prune resource
#1216

Fix arguments to generate_json in docker_image_prune resource

---

libraries/docker_installation_package.rb

Support Ubuntu 22.04 for module docker_installation_package
Resolving
[1224](https://github.com/sous-chefs/docker/issues/1224)

docker_installation_package: support for ubuntu 22.04

---

.github/workflows/ci.yml
CHANGELOG.md
kitchen.dokken.yml
kitchen.yml
metadata.rb
test/integration/install_and_stop/inspec/assert_functioning_spec.rb
test/integration/installation_package/inspec/assert_functioning_spec.rb

- Fix support for running on cgroupv2
- Split out amazonlinux-2 to Ubuntu 20.04 runner

Fix various CI issues

---

CHANGELOG.md
resources/service.rb

This PR fixes a bug, that properties of the `docker_service`-resource were passed to specific service management resource, which weren't defined there.
* #1248

[GH-1248] only pass common properties to service manager resources

---

CHANGELOG.md
resources/installation_package.rb

external website is not always available to all company due to firewall, security, etc.
Usually artifactory or other proxy to put in front to cache remote artifacts

Add download website property

---

.github/workflows/ci.yml
CHANGELOG.md
kitchen.dokken.yml
kitchen.global.yml
kitchen.yml
metadata.rb
resources/installation_package.rb
test/integration/install_and_stop/inspec/assert_functioning_spec.rb
test/integration/installation_package/inspec/assert_functioning_spec.rb

Bump docker-api gem dep to >= 2.3
- n/a

Bump docker-api gem dep to >= 2.3

---

CHANGELOG.md
resources/installation_package.rb

Fixes the `version_string` for Debian Bookworm.

Use correct Debian Bookworm version

---

.github/workflows/ci.yml
CHANGELOG.md
kitchen.yml
resources/service.rb
spec/docker_test/installation_package_spec.rb
test/cookbooks/docker_test/recipes/installation_package.rb
test/integration/install_and_stop/inspec/assert_functioning_spec.rb
test/integration/installation_package/inspec/assert_functioning_spec.rb

This is needed if you're trying to use the system packages and not the upstream
repository. This is useful for non-standard CPU architectures which might not
have upstream support.

Add none as an option to service_manager to allow using the system defaults

---

CHANGELOG.md
libraries/helpers_network.rb
resources/container.rb

- Added network mode normalization to handle container IDs consistently
- Prevents container recreation when only the container ID format changes
Resolves #1273

Fix issue with container network mode causing unnecessary redeployment

---

kitchen.dokken.yml
resources/installation_package.rb
spec/docker_test/installation_package_spec.rb

makes it so newer RHEL and Oracle can use the `rhel` platform yum repos.
I added Red Hat UBI 8 and 9 platforms to the `kitchen.dokken.yml` but I don't know if you want those or not.
fixes #1276

use rhel platform for all el8 and rhel 9+
