- .gitignore
- attributes/default.rb
This resolves https://github.com/bflad/chef-docker/issues/264
> Access keyserver.ubuntu.com on port 80

- templates/default/docker.sysconfig.erb
Minor generalization that allows interpolation of any embedded variables.
> Use double-quotes for DOCKER_OPTS

- spec/default_spec.rb
- spec/package_spec.rb
- spec/sysv_spec.rb
- spec/upstart_spec.rb
Running locally:
```
Pending: (Failures listed here are expected and do not affect your suite's status)
1) docker::default when running on ubuntu 12.04 should make sure kernel >= 3.8
Finished in 58.16 seconds (files took 1.93 seconds to load)
199 examples, 0 failures, 1 pending
```
> Rspec fixes mostly from #250 and #265 changes

- templates/default/docker.service.erb
- templates/default/docker.socket.erb
This updates the unit files to the latest state from upstream.
This pull request explains the details for the changes:
https://github.com/docker/docker/pull/8451
> Update systemd service/socket files

- README.md
A pipe needed escaping. Thanks for the cookbook -- great stuff!
> readme formatting fix

- CHANGELOG.md
- metadata.rb
> Release 0.37.0

- attributes/default.rb
- recipes/systemd.rb
- templates/default/docker.socket.erb
Adding attributes for Ubuntu 14.10 plus systemd-specific changes for Ubuntu 15.04
tested on Ubuntu 15.04 beta3.  overlayfs woohoo!
> Updates for Ubuntu 14.10 and 15.04

- templates/default/docker.conf.erb
Fixes:
https://github.com/docker/docker/commit/302e3834a0bfa860f9d06b42a2955b0cbd135c38#diff-1c707368b6816877883a5e2633bceebb
https://github.com/docker/docker/commit/2f9e7a067a7273a0f344c1c9a6397e4bb61d7554#diff-1c707368b6816877883a5e2633bceebb
> Update docker daemon upstart job with upstream configuration

- templates/default/docker-container.conf.erb
> Fix for restart not working in container upstart job

- .kitchen.yml
- libraries/resource_docker_service.rb
- test/integration/resources/serverspec/assert_functioning_spec.rb
> Docker service tls fix

- .kitchen.yml
- libraries/_port_binding.rb
- libraries/provider_docker_container.rb
> Update port attribute to allow an array to be passed in

- libraries/helpers.rb
> fix logic for parsing an array of hosts

- libraries/helpers.rb
- templates/default/1.6/systemd/docker.service.erb
- templates/default/1.6/sysvinit/docker.erb
- templates/default/1.6/upstart/etc.default.docker.erb
- templates/default/1.7/systemd/docker.service.erb
- templates/default/1.7/sysvinit/docker.erb
- templates/default/1.7/upstart/etc.default.docker.erb
- templates/default/1.8/systemd/docker.service.erb
- templates/default/1.8/sysvinit/docker.erb
- templates/default/1.8/upstart/etc.default.docker.erb
* Removes prepended whitespace in each string listed under docker_opts
* Uses #join to produce the docker_daemon_cmn
* Uses #join to render docker_opts in templates
> [GH-380] Remove prepended whitespce in DOCKER_OPTS

- libraries/helpers.rb
- libraries/resource_docker_service.rb
> allowing storage_driver to be an array

- templates/default/1.6/upstart/docker.conf.erb
- templates/default/1.7/upstart/docker.conf.erb
- templates/default/1.8/upstart/docker.conf.erb
> setting sane respawn limit

- libraries/helpers_service.rb
- spec/docker_service_test/socket_spec.rb
Change Docker binary download URL to use HTTPS.
> Download Docker binary over HTTPS

- libraries/provider_docker_container.rb
- libraries/resource_docker_service.rb
> Whitespace fixes for rubocop happiness.

- libraries/helpers_container.rb
Missing changeset for PR #443. Should also fix #444.
> Final fix for PR #443.

- libraries/helpers_service.rb
> fix to set allow icc to be set false

- libraries/helpers_service.rb
- libraries/resource_docker_service.rb
> default_ulimit is now type string or array

- libraries/helpers_container.rb
- libraries/provider_docker_container.rb
- libraries/resource_docker_container.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-182/serverspec/assert_functioning_spec.rb
> adding the option labels to containers

- test/cookbooks/docker_test/files/default/Dockerfile_4
- test/cookbooks/docker_test/recipes/image.rb
As requested in the issue, here is the PR with the new test case.
> Added test case for Issue #458 - timeout during docker_image :build_if_missing

- libraries/helpers_service.rb
sorry this should have tested against nil since we need false as an output.
resolves #462
> icc should test against nil

- libraries/provider_docker_service_sysvinit.rb
- templates/default/sysvinit/docker.erb
> updating sysvinit to use docker_opts

- libraries/provider_docker_container.rb
> fix for redeploy on missing containers

- libraries/helpers_image.rb
> Fall back to creds for index.docker.io on image pull

- libraries/docker_service.rb
- libraries/helpers_service.rb
this could probably be done a lot better, but it works for now.
resolves #488
> return best host for docker to connect to

- libraries/helpers_service.rb
the boolean property should be passed through instead of forcing it to be true/false. originally i was only fixing iptables, but i decided to fix the remaining as well.
resolves #494
> opts shouldnt be forced to true/false

- libraries/docker_image.rb
- libraries/helpers_image.rb
> Revert "Use with_retries and load_current_value in DockerImage"

- libraries/docker_container.rb
- libraries/helpers_container.rb
> stop and start should wait for the container to complete

- test/cookbooks/docker_test/recipes/registry.rb
hopefully this resolves #508 for good. let me know if it doesnt though and ill circle back around on it.
> wait for registry ports to be open

- README.md
> update readme to include labels for containers

- libraries/docker_service.rb
> dont enable https if we arent using tls

- .kitchen.yml
- libraries/docker_container.rb
- libraries/helpers_base.rb
- test/cookbooks/docker_service_test/recipes/default.rb
- test/cookbooks/docker_service_test/recipes/sysvinit.rb
- test/cookbooks/docker_service_test/recipes/tcp-tls.rb
- test/cookbooks/docker_service_test/recipes/tcp.rb
- test/integration/service-default/serverspec/assert_functioning_spec.rb
- test/integration/service-tcp-tls/serverspec/assert_functioning_spec.rb
- test/integration/service-tcp/serverspec/assert_functioning_spec.rb
> a couple of docker calls were missing the connection. refactored service tests.

- README.md
- libraries/docker_container.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-162/serverspec/assert_functioning_spec.rb
- test/integration/resources-171/serverspec/assert_functioning_spec.rb
- test/integration/resources-182/serverspec/assert_functioning_spec.rb
> passing invalid param for timeout on container stop

- README.md
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-182/serverspec/assert_functioning_spec.rb
ive got a lovely bunch of coconuts
> fixing kitchen and rspec to gracefully kill containers

- README.md
- libraries/docker_base.rb
- libraries/docker_container.rb
- libraries/docker_image.rb
- libraries/helpers_base.rb
> support for using docker ENV variables

- test/integration/resources-162/serverspec/assert_functioning_spec.rb
- test/integration/resources-171/serverspec/assert_functioning_spec.rb
- test/integration/resources-183/serverspec/assert_functioning_spec.rb
- test/integration/resources-190/serverspec/assert_functioning_spec.rb
this fixes inspec failing out during kitchen runs.
> updating spec to check stdout of docker ps. exit_status always returns 0

- libraries/helpers_base.rb
> tls and tls_verify should be nil by default

- README.md
- libraries/docker_service_base.rb
- libraries/helpers_service.rb
This PR will add support to the docker service library for clustering store daemon arguments.
> Add cluster-store options to docker daemon

- libraries/helpers_container.rb
- spec/docker_test/container_spec.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-162/serverspec/assert_functioning_spec.rb
- test/integration/resources-171/serverspec/assert_functioning_spec.rb
- test/integration/resources-183/serverspec/assert_functioning_spec.rb
- test/integration/resources-190/serverspec/assert_functioning_spec.rb
> adding support for port range

- .kitchen.yml
- README.md
i use centos heavily so i'd like to keep test kitchen runs happy with centos :grin:
> updating centos to 7.1

- README.md
- libraries/docker_container.rb
- libraries/helpers_container.rb
- spec/docker_test/container_spec.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-162/serverspec/assert_functioning_spec.rb
- test/integration/resources-171/serverspec/assert_functioning_spec.rb
- test/integration/resources-183/serverspec/assert_functioning_spec.rb
- test/integration/resources-191/serverspec/assert_functioning_spec.rb
Reverts chef-cookbooks/docker#590
> Revert "parse binds to match docker cli parsing of -v"

- README.md
- libraries/docker_service_base.rb
- libraries/helpers_service.rb
> disable-legacy-registry

- libraries/helpers_image.rb
> reverting 15db713

- libraries/docker_container.rb
- libraries/helpers_container.rb
> links unordered array

- libraries/docker_container.rb
> making conditionals stricter on container validation

- libraries/docker_service.rb
> coffee makes the brain smarter. flipping or to and.

- libraries/docker_network.rb
- libraries/helpers_network.rb
- spec/docker_test/network_spec.rb
- spec/helpers_network_spec.rb
- test/cookbooks/docker_test/recipes/network.rb
- test/integration/network/serverspec/assert_functioning_spec.rb
This will also add a couple of tests. This will create test duplicates. Issue #645
> Fix aux error in docker network

- README.md
- libraries/docker_installation_package.rb
- libraries/docker_service.rb
Related to https://github.com/chef-cookbooks/docker/issues/647
> package options

- README.md
> typo in doc

- libraries/docker_container.rb
- libraries/docker_service_base.rb
> extending available log_driver options

- libraries/docker_container.rb
> track state of binds property

- libraries/docker_container.rb
> run container if it doesnt exist yet

- spec/docker_test/container_spec.rb
- spec/docker_test/network_spec.rb
- test/cookbooks/docker_test/recipes/container.rb
this will speed up a couple of tests in kitchen
also test coverage for the german network
> change commands from nc to trap

- libraries/docker_service_base.rb
- libraries/helpers_service.rb
> insecure registry can now be passed as an array

- libraries/helpers_installation_package.rb
Add Ubuntu 16.04 to helper package to begin 16.04 support
> Add Ubuntu 16.04 Xenial to package helper

- README.md
- libraries/docker_container.rb
Implement userns_mode on docker_container resource
#722 submitted by myself
> User namespace support for docker_container resource

- README.md
This makes it easier to jump to the specific part of the readme. related to #650
> Add links to resources overview list

- README.md
[Describe what this change achieves]
[List any existing issues this PR resolves]
> entrypoint not entry_point

- libraries/matchers.rb
Add matchers for `docker_installation_tarball`
NA
> Add matchers for docker_installation_tarball

- libraries/docker_container.rb
> fixing resource idempotence in labels property

- Gemfile
- README.md
- libraries/docker_network.rb
- spec/docker_test/network_spec.rb
- test/cookbooks/docker_test/recipes/network.rb
- test/integration/network/inspec/assert_functioning_spec.rb
Implement `:connect` and `:disconnect` actions for `docker_network` resource.
None.
> Implement network connect/disconnect

- libraries/helpers_image.rb
Reverts chef-cookbooks/docker#733
> Revert "Fix pull from private dockerhub repository"

- templates/default/upstart/docker.conf.erb
Fix ubuntu upstart script
#797
> Fix ubuntu upstart script

- CHANGELOG.md
- metadata.rb
> updating CHANGELOG and bumping metadata

- spec/docker_test/container_spec.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-1123/inspec/assert_functioning_spec.rb
> Attempting to replicate #673

- metadata.rb
- test/cookbooks/docker_test/metadata.rb
[Describe what this change achieves]
[List any existing issues this PR resolves]
> Use a SPDX standard license string

- README.md
- libraries/docker_service_base.rb
- libraries/docker_service_manager_systemd.rb
- templates/default/systemd/docker.service-override.erb
- templates/default/systemd/docker.service.erb
- fix docker socket group being empty
- bring systemd unit file closer to stock
> update systemd unit file

- libraries/docker_service_manager_sysvinit_debian.rb
- libraries/docker_service_manager_upstart.rb
- templates/default/default/docker.erb
- templates/default/sysconfig/docker.erb
- templates/default/sysvinit/docker-debian.erb
- templates/default/upstart/docker.conf.erb
adding restart notifications to upstart and cleaning house on the configs
> adding restart notifications to upstart

- libraries/docker_service_manager_systemd.rb
- libraries/docker_service_manager_upstart.rb
- libraries/helpers_service.rb
- templates/default/systemd/docker.service-override.erb
- templates/default/systemd/docker.service.erb
> fix for docker_service not containing a listening socket

- libraries/helpers_container.rb
- spec/docker_test/container_spec.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-17060/inspec/assert_functioning_spec.rb
this adds functionality for the host port to be a range that matches with the container port range.
resolves #830
> host port range

- README.md
> Update with the new default value

- .gitignore
- .kitchen.yml
- Berksfile
- libraries/docker_network.rb
- libraries/docker_service.rb
- metadata.rb
> Fail on deprecations in Travis

- libraries/_autoload.rb
> Use docker-api 1.33.6

- README.md
> Update maintainers in the readme

- README.md
- libraries/docker_container.rb
- libraries/helpers_container.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-17062/inspec/assert_functioning_spec.rb
> adding support for env_file

- README.md
- libraries/docker_container.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources-17090/inspec/assert_functioning_spec.rb
> add init support to docker_container, issue #934

- libraries/docker_base.rb
- libraries/docker_container.rb
- libraries/docker_exec.rb
- libraries/docker_image.rb
- libraries/docker_network.rb
- libraries/docker_volume.rb
> Remove the TLS default helpers

- libraries/docker_base.rb
- libraries/docker_container.rb
> Move coerce_labels into docker_container where its used

- libraries/docker_installation_package.rb
Should be pretty straightforward 💅
> Fix typo in docker yum repo file

- Gemfile
- libraries/docker_container.rb
- libraries/docker_service.rb
- libraries/docker_service_manager_systemd.rb
Many fixes to make it work with Chef 14.
Fixes #989 #986 #983
> Chef14 fixes

- kitchen.yml
- libraries/docker_installation_package.rb
- libraries/docker_installation_tarball.rb
- libraries/docker_volume.rb
- spec/docker_test/installation_package_spec.rb
- spec/docker_test/service_spec.rb
- test/cookbooks/docker_test/recipes/installation_package.rb
- test/integration/installation_package/inspec/assert_functioning_spec.rb
- test/integration/installation_tarball/inspec/assert_functioning_spec.rb
- test/integration/resources/inspec/assert_functioning_spec.rb
of course docker has changed its naming schema again
> version bump to 18.06.0

- libraries/docker_installation_package.rb
- spec/docker_test/installation_package_spec.rb
Support for docker version 18.09 which uses a different package naming convention
https://github.com/chef-cookbooks/docker/issues/1036
> Docker version 18.09

- README.md
- libraries/docker_image_prune.rb
- spec/docker_test/image_prune_spec.rb
- spec/libraries/image_prune_spec.rb
- test/cookbooks/docker_test/recipes/image_prune.rb
Implements Image Pruning
https://docs.docker.com/engine/api/v1.35/#operation/ImagePrune
https://docs.docker.com/engine/reference/commandline/image_prune/
https://github.com/chef-cookbooks/docker/issues/956
- [ X] New functionality has been documented in the README if applicable
> Image prune

- libraries/docker_container.rb
- spec/docker_test/container_spec.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/cookbooks/docker_test/recipes/image_prune.rb
lint fixes only
n/a
- [x ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x ] New functionality includes testing.
- [x ] New functionality has been documented in the README if applicable
- [x ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>
> lint fixes only

- libraries/docker_container.rb
- spec/libraries/container_networks_spec.rb
- spec/libraries/container_spec.rb
- spec/libraries/image_prune_spec.rb
- test/cookbooks/docker_test/recipes/container.rb
* Adds chefspec tests for creating containers to ensure the json passed to the docker API is what we expect
* lint fixes
* Fix when HealthCheck is used for #1043
* Support for windows
Fix when HealthCheck is used for #1043
- [ X] New functionality has been documented in the README if applicable
> Chefspec tests for creating containers and windows support

- .travis.yml
- kitchen.yml
> Remove Ubuntu 14.04 testing, update fedora testing, fix amazon 2 testing

- libraries/docker_volume.rb
This fixes issue #1061 that I reported. I have tested this manually, but not had a chance to follow the testing instructions.
- #1061
> fixes issue #1061, docker_volume 'driver' and 'opts' don't work and this

- README.md
Fixing a documentation issue in docker_image
> Update docker_image doc to fix escaping typo

- libraries/docker_container.rb
Signed-off-by: Kapil Chouhan <kapil.chouhan@msystechnologies.com>
- In the Chef 15 we reset desired-state properties https://github.com/chef/chef/blob/v15.7.30/lib/chef/resource/action_class.rb#L45, but in Chef 16 we set it https://github.com/chef/chef/blob/master/lib/chef/resource/action_class.rb#L41
- So our docker_container property `env_file` coerce was returning the content of the file, not a file path, due to this https://github.com/chef/chef/blob/master/lib/chef/resource/action_class.rb#L41 it calls again `env_file` coerce with the file content, so at that time it was giving an error `No such file or directory @ rb_sysopen`
Fixes: #1106
> Fix for env_file breaks on Chef 16

- .github/CODEOWNERS
- CHANGELOG.md
> Fix codeowners

- CHANGELOG.md
- libraries/docker_base.rb
- libraries/docker_image.rb
Stomp my feet on #1142, forked https://github.com/sous-chefs/docker/pull/1143 hoping to get it merged soon.
Thanks!
> Fix private registries credentials handling and public registries

- CHANGELOG.md
- resources/container.rb
- resources/partial/_base.rb
- resources/partial/_logging.rb
Move the logging config to a partial so that it can be reused
NA
> Move the logging config to a partial so that it can be reused

- .delivery/project.toml
- .github/workflows/ci.yml
- .overcommit.yml
- CHANGELOG.md
- kitchen.dokken.yml
- kitchen.yml
- spec/docker_test/service_spec.rb
This PR will standardise the files we have with out agreed spec in sous-chefs/repo-management.
This repo has been identified by topic(s) of chef-cookbook
> Automated PR: Standardising Files

- README.md
Signed-off-by: Jason Field <jason@avon-lea.co.uk>
> force-release

- CHANGELOG.md
- metadata.rb
Makes the cookbook work again.
- n/a
> Version pin excon to v0.110.0

- CHANGELOG.md
> Bump changelog to trigger a new release

- CHANGELOG.md
- documentation/docker_service.md
- libraries/helpers_service.rb
- resources/partial/_service_base.rb
> add opts for ip6tables

- CHANGELOG.md
- documentation/docker_container.md
- resources/container.rb
- test/cookbooks/docker_test/recipes/container.rb
- test/integration/resources/inspec/assert_functioning_spec.rb
> Docs: update docs for tmpfs

- CHANGELOG.md
- resources/container.rb
Signed-off-by: Dan Webb <dan.webb@damacus.io>
> Add support for 256 image digests

- .github/workflows/ci.yml
- CHANGELOG.md
- kitchen.global.yml
- kitchen.yml
- resources/container.rb
- resources/image.rb
- resources/installation_package.rb
- spec/docker_test/installation_package_spec.rb
- test/cookbooks/docker_test/recipes/smoke.rb
- Fix sha256 tag references
- Update smoke test recipe to work with an image that will stay running
> Set signed_by property in apt_repository to false on platforms that do not support it

- CHANGELOG.md
- resources/installation_package.rb
> Only use signed_by property if using the Chef Infra Client 18.7.10 and above
